### ISSUE TITLE
current_week() failing

### ISSUE THREAD

**Issue by ramGoli** [amarvin/fantasy-football-bot#72]
```
>>> week = ffbot.current_week()

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/lib/python3.11/site-packages/ffbot/scraper.py", line 183, in current_week
    week = span.text.split()[1]
           ^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'
```

is it because the league hasn't started yet ?

**Comment by amarvin** [comment]
Thanks for reporting this. It should be resolved if you update to the latest release v1.2.1. If it doesn't work for you, please reopen this issue.

**Comment by bear-da** [comment]
This is no longer working as it is not allowing me to view the new public league.

**Comment by bear-da** [comment]
I can access the public league via https://football.fantasysports.yahoo.com/f1/16 but am still not getting any results.
